name: MoveFiles_build_main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.Smb.MoveFiles/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.Smb.MoveFiles
      dotnet_version: 8.0.x
      strict_analyzers: true
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
